

services:
  # Servis 1: Python
  data-generator:
    build: ./data-generator
    expose:
      - "8000"

  # Servis 2: Node.js
  aggregator:
    build: ./aggregator
    ports:
      - "3000:3000" # Bilgisayarındaki 3000 portunu konteynere bağlar
    depends_on:
      - data-generator # Önce Python servisinin açılmasını sağlardocker-compose up --build